//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NC_Reactor_Planner.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string FissionPower {
            get {
                return ((string)(this["FissionPower"]));
            }
            set {
                this["FissionPower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string FuelUse {
            get {
                return ((string)(this["FuelUse"]));
            }
            set {
                this["FuelUse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.2")]
        public string HeatGeneration {
            get {
                return ((string)(this["HeatGeneration"]));
            }
            set {
                this["HeatGeneration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string ModeratorExtraPower {
            get {
                return ((string)(this["ModeratorExtraPower"]));
            }
            set {
                this["ModeratorExtraPower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string ModeratorExtraHeat {
            get {
                return ((string)(this["ModeratorExtraHeat"]));
            }
            set {
                this["ModeratorExtraHeat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public string NeutronReach {
            get {
                return ((string)(this["NeutronReach"]));
            }
            set {
                this["NeutronReach"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Exist {
            get {
                return ((bool)(this["Exist"]));
            }
            set {
                this["Exist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Water {
            get {
                return ((string)(this["Water"]));
            }
            set {
                this["Water"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Redstone {
            get {
                return ((string)(this["Redstone"]));
            }
            set {
                this["Redstone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Quartz {
            get {
                return ((string)(this["Quartz"]));
            }
            set {
                this["Quartz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Gold {
            get {
                return ((string)(this["Gold"]));
            }
            set {
                this["Gold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Glowstone {
            get {
                return ((string)(this["Glowstone"]));
            }
            set {
                this["Glowstone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Lapis {
            get {
                return ((string)(this["Lapis"]));
            }
            set {
                this["Lapis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Diamond {
            get {
                return ((string)(this["Diamond"]));
            }
            set {
                this["Diamond"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Helium {
            get {
                return ((string)(this["Helium"]));
            }
            set {
                this["Helium"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Enderium {
            get {
                return ((string)(this["Enderium"]));
            }
            set {
                this["Enderium"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Cryotheum {
            get {
                return ((string)(this["Cryotheum"]));
            }
            set {
                this["Cryotheum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Iron {
            get {
                return ((string)(this["Iron"]));
            }
            set {
                this["Iron"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Emerald {
            get {
                return ((string)(this["Emerald"]));
            }
            set {
                this["Emerald"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Copper {
            get {
                return ((string)(this["Copper"]));
            }
            set {
                this["Copper"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Tin {
            get {
                return ((string)(this["Tin"]));
            }
            set {
                this["Tin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Magnesium {
            get {
                return ((string)(this["Magnesium"]));
            }
            set {
                this["Magnesium"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TBU {
            get {
                return ((string)(this["TBU"]));
            }
            set {
                this["TBU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TBU__Oxide {
            get {
                return ((string)(this["TBU__Oxide"]));
            }
            set {
                this["TBU__Oxide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LEU_233 {
            get {
                return ((string)(this["LEU_233"]));
            }
            set {
                this["LEU_233"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LEU_233__Oxide {
            get {
                return ((string)(this["LEU_233__Oxide"]));
            }
            set {
                this["LEU_233__Oxide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HEU_233 {
            get {
                return ((string)(this["HEU_233"]));
            }
            set {
                this["HEU_233"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HEU_233__Oxide {
            get {
                return ((string)(this["HEU_233__Oxide"]));
            }
            set {
                this["HEU_233__Oxide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LEU_235 {
            get {
                return ((string)(this["LEU_235"]));
            }
            set {
                this["LEU_235"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LEU_235__Oxide {
            get {
                return ((string)(this["LEU_235__Oxide"]));
            }
            set {
                this["LEU_235__Oxide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HEU_235 {
            get {
                return ((string)(this["HEU_235"]));
            }
            set {
                this["HEU_235"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HEU_235__Oxide {
            get {
                return ((string)(this["HEU_235__Oxide"]));
            }
            set {
                this["HEU_235__Oxide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LEN_236 {
            get {
                return ((string)(this["LEN_236"]));
            }
            set {
                this["LEN_236"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LEN_236__Oxide {
            get {
                return ((string)(this["LEN_236__Oxide"]));
            }
            set {
                this["LEN_236__Oxide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HEN_236 {
            get {
                return ((string)(this["HEN_236"]));
            }
            set {
                this["HEN_236"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HEN_236__Oxide {
            get {
                return ((string)(this["HEN_236__Oxide"]));
            }
            set {
                this["HEN_236__Oxide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LEP_239 {
            get {
                return ((string)(this["LEP_239"]));
            }
            set {
                this["LEP_239"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LEP_239__Oxide {
            get {
                return ((string)(this["LEP_239__Oxide"]));
            }
            set {
                this["LEP_239__Oxide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HEP_239 {
            get {
                return ((string)(this["HEP_239"]));
            }
            set {
                this["HEP_239"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HEP_239__Oxide {
            get {
                return ((string)(this["HEP_239__Oxide"]));
            }
            set {
                this["HEP_239__Oxide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LEP_241 {
            get {
                return ((string)(this["LEP_241"]));
            }
            set {
                this["LEP_241"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LEP_241__Oxide {
            get {
                return ((string)(this["LEP_241__Oxide"]));
            }
            set {
                this["LEP_241__Oxide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HEP_241 {
            get {
                return ((string)(this["HEP_241"]));
            }
            set {
                this["HEP_241"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HEP_241__Oxide {
            get {
                return ((string)(this["HEP_241__Oxide"]));
            }
            set {
                this["HEP_241__Oxide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MOX_239 {
            get {
                return ((string)(this["MOX_239"]));
            }
            set {
                this["MOX_239"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MOX_241 {
            get {
                return ((string)(this["MOX_241"]));
            }
            set {
                this["MOX_241"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LEA_242 {
            get {
                return ((string)(this["LEA_242"]));
            }
            set {
                this["LEA_242"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LEA_242__Oxide {
            get {
                return ((string)(this["LEA_242__Oxide"]));
            }
            set {
                this["LEA_242__Oxide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HEA_242 {
            get {
                return ((string)(this["HEA_242"]));
            }
            set {
                this["HEA_242"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HEA_242__Oxide {
            get {
                return ((string)(this["HEA_242__Oxide"]));
            }
            set {
                this["HEA_242__Oxide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LECm_243 {
            get {
                return ((string)(this["LECm_243"]));
            }
            set {
                this["LECm_243"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LECm_243__Oxide {
            get {
                return ((string)(this["LECm_243__Oxide"]));
            }
            set {
                this["LECm_243__Oxide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HECm_243 {
            get {
                return ((string)(this["HECm_243"]));
            }
            set {
                this["HECm_243"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HECm_243__Oxide {
            get {
                return ((string)(this["HECm_243__Oxide"]));
            }
            set {
                this["HECm_243__Oxide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LECm_245 {
            get {
                return ((string)(this["LECm_245"]));
            }
            set {
                this["LECm_245"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LECm_245__Oxide {
            get {
                return ((string)(this["LECm_245__Oxide"]));
            }
            set {
                this["LECm_245__Oxide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HECm_245 {
            get {
                return ((string)(this["HECm_245"]));
            }
            set {
                this["HECm_245"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HECm_245__Oxide {
            get {
                return ((string)(this["HECm_245__Oxide"]));
            }
            set {
                this["HECm_245__Oxide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LECm_247 {
            get {
                return ((string)(this["LECm_247"]));
            }
            set {
                this["LECm_247"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LECm_247__Oxide {
            get {
                return ((string)(this["LECm_247__Oxide"]));
            }
            set {
                this["LECm_247__Oxide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HECm_247 {
            get {
                return ((string)(this["HECm_247"]));
            }
            set {
                this["HECm_247"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HECm_247__Oxide {
            get {
                return ((string)(this["HECm_247__Oxide"]));
            }
            set {
                this["HECm_247__Oxide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LEB_248 {
            get {
                return ((string)(this["LEB_248"]));
            }
            set {
                this["LEB_248"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LEB_248__Oxide {
            get {
                return ((string)(this["LEB_248__Oxide"]));
            }
            set {
                this["LEB_248__Oxide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HEB_248 {
            get {
                return ((string)(this["HEB_248"]));
            }
            set {
                this["HEB_248"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HEB_248__Oxide {
            get {
                return ((string)(this["HEB_248__Oxide"]));
            }
            set {
                this["HEB_248__Oxide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LECf_249 {
            get {
                return ((string)(this["LECf_249"]));
            }
            set {
                this["LECf_249"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LECf_249__Oxide {
            get {
                return ((string)(this["LECf_249__Oxide"]));
            }
            set {
                this["LECf_249__Oxide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HECf_249 {
            get {
                return ((string)(this["HECf_249"]));
            }
            set {
                this["HECf_249"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HECf_249__Oxide {
            get {
                return ((string)(this["HECf_249__Oxide"]));
            }
            set {
                this["HECf_249__Oxide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LECf_251 {
            get {
                return ((string)(this["LECf_251"]));
            }
            set {
                this["LECf_251"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LECf_251__Oxide {
            get {
                return ((string)(this["LECf_251__Oxide"]));
            }
            set {
                this["LECf_251__Oxide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HECf_251 {
            get {
                return ((string)(this["HECf_251"]));
            }
            set {
                this["HECf_251"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HECf_251__Oxide {
            get {
                return ((string)(this["HECf_251__Oxide"]));
            }
            set {
                this["HECf_251__Oxide"] = value;
            }
        }
    }
}
